# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 584875545f8f2abb1043e85bca94bb078da38c5952d9e6a3dcaaff6758a1c93d995823cce11fba32e2367c88fe1a1bd96967aa0d11d7438ffb22729284a94e13

test:
  secret_key_base: 170b37b52de94725bc134a2351be339653e3c1853ed912a2ddc68fba7fca0038e6280ebbbddb0394b4a754186e737f4dec62a4b20a0f286680f641209fee329e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
